### ISSUE TITLE
支持 protobuf

### ISSUE THREAD

**Issue by ylgrgyq** [leancloud/Play-SDK-JS#117]
~关联：https://github.com/leancloud/leangame/issues/302~

~详细说明在上面的链接里。~

**Comment by ylgrgyq** [comment]
上面链接内容不再适用，请参看 wiki 吧。
https://github.com/leancloud/leangame/wiki/Protobuf-%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/219
