### ISSUE TITLE
设置属性时，在 then 里面可以拿到最新的属性值

### ISSUE THREAD

**Issue by nicecui** [leancloud/Play-SDK-JS#170]
- [x] 房间 open
- [x] 房间 visible
- [x] 房间自定义属性
- [x] player 的自定义属性
- [x] setMaster
- [x] 踢人的应答中可以拿到房间的最新成员信息

**Comment by onerain88** [comment]
补充一下：踢人是否也应该是一致的机制，应答里也加入踢人的信息

**Comment by nicecui** [comment]
* setMaster

**Comment by onerain88** [comment]
踢人的应答里应该是「被踢人的信息」吧，由 sdk 计算出最新成员信息

**Comment by ylgrgyq** [comment]
踢人只有成功信息，没有别的信息的。踢人时要传递你要踢谁，返回成功的含义就是这个人被踢出去了，SDK 本身是知道自己在踢谁的。

**Comment by onerain88** [comment]
这个还是建议下发下来，「以服务端为准」。
否则，对于其他请求（比如房间的可见 / 关闭），客户端也都是「可以运算的」，都没必要下发了。

**Comment by ylgrgyq** [comment]
房间属性，player 属性，设置 master 目前返回值就会带着最新修改值。剩下三个需要补充一下。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/176
