### ISSUE TITLE
sendEvent 捕捉 catch 错误

### ISSUE THREAD

**Issue by nicecui** [leancloud/Play-SDK-JS#173]
```
client.sendEvent('startGame', {}, {receiverGroup: ReceiverGroup.All}).then().catch();
```

玩家不在房间时发送事件，Promise 应该到 catch 中：
* 玩家未 connect 时发送事件
* 玩家 connect 成功后发送事件
* 玩家在 joinLoby 后发送事件

在这些应该失败的场景下，都走到了 then 中。这里应该都是 SDK 的工作，需要 SDK 根据状态判断是否应该发送事件，如果不应该则返回 error。

**Comment by onerain88** [comment]
嗯，这里是没有在「非 Game 连接状态」下对于事件的处理，我补充一下。

**Comment by onerain88** [comment]
但是由于 sendEvent() 的应答是「配置的」，所以只能在 SDK 层面做状态判断，如果服务端认为此次请求非法，会通过 cmd=Error 通知客户端

**Comment by nicecui** [comment]
已修复
