### ISSUE TITLE
Client 增加 isMessageQueueRunning 属性，控制 SDK 是否处理消息

### ISSUE THREAD

**Issue by onerain88** [leancloud/Play-SDK-JS#181]
## 使用场景：
在游戏加载场景时（比如从主界面到战斗场景），中间会有加载资源等异步操作。如果此过程 SDK 持续将「事件」分发给开发者，开发者将需要缓存，等到加载到战斗场景后才能处理（比如在加载过程中，有其他人加入，或者其他交互事件）。

## 接口作用：
这个接口的目的为「暂停」事件分发，先将消息缓存起来，等到设置为 true 时再交由开发者处理。
这个接口名字是参考的 photon，感觉是否叫 pause / resume 会好一些？大家有什么意见？
@leeyeh @nicecui 

## 注意：
心跳消息正常接收，避免超时被服务端踢下线。
断线后清空缓存，即每次连接时清空缓存的消息队列。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/183

**Comment by leeyeh** [comment]
Photon 的 `isMessageQueueRunning` 属性是要怎么用？

`client.pause()` / `client.resume()` 看不出来是跟消息下发有关，需要更明确的命名。

**Comment by onerain88** [comment]
```csharp
PhotonNetwork.isMessageQueueRunning = false // PhotonNetwork 类比我们之前的 Play
```
我们需要设计到 Client 的成员属性中

**Comment by onerain88** [comment]
或者 pauseMessageQueue() / resumeMessageQueue()

**Comment by leeyeh** [comment]
通过两个方法来控制功能的开始与停止我可以理解，Photon 是怎么通过一个属性来做到的呢？其实是个 setter？从 `isMessageQueueRunning` 的命名看，似乎更像是个只读的状态？

**Comment by onerain88** [comment]
包含 get 和 set
http://doc-api.photonengine.com/en/PUN/current/class_photon_network.html#a9cf8214080471001a1a32e17eff9b402

**Comment by leeyeh** [comment]
pause 的感觉是，原来有一个正常运行的东西（queue），现在你给他暂停了。

如果 Client 本身是一个 consumer 抽象的话，这样 pause / resume 是解释的通的。但我们现在 Client 是一个 EventEmitter，而且在 RTM 里已经引入了 pause  / resume 来表示连接的暂停与恢复，容易引起混乱。

所以可能叫长一点精确一点，startEventQueue / stopEventQueue ？

**Comment by onerain88** [comment]
我理解 startXX 是启动的意思，但是这里默认是运行的，只是有时候需要暂停，所以一般情况下是先 pause，在 resume，成对出现。
如果是 start 和 stop，感觉应该先 start，再 stop

**Comment by onerain88** [comment]
还有一点，我这里建议用的 pauseMessageQueue，Message 认为是比 Event 更低层次的通信消息，Event 认为是给用户的事件，更高级一些。
这里的 pause，会导致 request - response 也不会应答

**Comment by leeyeh** [comment]
pauseMessageQueue 的意思是，你原来有个队列在运行（并没有），现在暂停这个队列。不是很说得通。

**Comment by onerain88** [comment]
其实我认为是一致在有消息队列处理的，只是接收到消息后立即处理了，并没有放到队列中，然后再交由其他循环处理。
为了避免这个疑惑，是不是可以叫 pauseHandlingMessage / resumeHandlingMessage。

request-response 不应答，是为了保证消息的「有序性」。

**Comment by leeyeh** [comment]
Let's do pauseMessageQueue / resumeMessageQueue.

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/releases/tag/v0.18.0-alpha.7
