### ISSUE TITLE
加入房间时，由于加入（创建）请求应答的异步，影响了后面推送消息的处理

### ISSUE THREAD

**Issue by onerain88** [leancloud/Play-SDK-JS#184]
创建 / 加入房间分为以下几个「异步」过程：

1. 在 lobby 上请求创建 / 加入房间
2. 与 game 服务器建立连接
3. 在 game 上请求 open session
4. 在 game 上请求创建 / 加入房间
5. 断开与 lobby 的连接
6. 创建 / 加入房间完成

当前实现方法，封装一个返回 Promise 对象的 joinRoom()。在 Promise 中，会顺序执行上述 6 个步骤，最后 resolve()。
问题，在 4 步骤以后，连接已经建立，则此时有可能「服务端主动推送某些消息」。而这些消息，会插在上述 resolve() 之前。
则有可能导致的逻辑描述为：在创建 / 加入房间之前，收到房间属性修改，玩家属性修改等事件。

解决方法：
在第 4 步骤完成后，暂停 game 消息处理，等待第 6 步骤完成后，再恢复 game 消息处理。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/185

**Comment by nicecui** [comment]
补充说明：
我在加入房间时的期望步骤如下：
1. client 加入房间成功，then 被触发
2. 使用 SDK 的接口 pauseMessageQueue 停住消息
3. 切换场景，加载过场动画
  3.1 此时 MasterClient 修改了当前 client 的属性
4. 动画加载完成，使用 resumeMessageQueue 恢复消息
5. 接收到消息：MasterClient 修改了当前 client 的属性

在这个场景当中，有概率发生这种 Bug：SDK 的 then 未触发时，MasterClient 就修改了房间属性。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/186
