### ISSUE TITLE
接口调整

### ISSUE THREAD

**Issue by onerain88** [leancloud/Play-SDK-JS#190]
总结了一下「当前的 API」，感觉在易用性和理解上需要做些调整，我先把能想到的问题列出来，请大家补充。
@leeyeh @nicecui

**Comment by onerain88** [comment]
接口归属问题

比如之前讨论过的，目前几乎所有接口都在 Client 上，并不够精确，但是提供了调用的便捷性。
所以我的预期是在每个类上提供接口，文档也这样描述；但是 Client 类上也提供对应接口，带来一些便捷性。（比如对于房间属性的修改等）

**Comment by onerain88** [comment]
创建 / 加入房间的 Promise 接口返回 Room 对象，方便后续操作

**Comment by onerain88** [comment]
统一获取只读属性的访问方式

**Comment by nicecui** [comment]
之前优化把获取 userId 的接口优化没了，导致加入房间前无法告知其他人自己的 userId，需要增加获取 userId 的接口。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/191

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/releases/tag/v0.18.0-beta.0
