### ISSUE TITLE
需要连接本地 router 的方法

### ISSUE THREAD

**Issue by nicecui** [leancloud/Play-SDK-JS#201]
目前 game 服务端代码可以在本地跑起来了，但是本地测试 hook 代码的话还需要客户端的 SDK 指定服务器地址。

**Comment by onerain88** [comment]
需要确定以下问题：

- 这个地址是指「大厅服务器」和「游戏服务器」的地址吗？是单独设置？还是设置成一个？

- 是否还允许配置最初的 http router？由 http router 来路由到后台配置的 server 地址。

@ylgrgyq @nicecui @leeyeh

**Comment by ylgrgyq** [comment]
本地测试过程与线上一致。所以，这里 SDK 需要设置的是 Game Router 的地址，依然是通过 Game Router 对用户做路由，只是路由到自己本地。

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/202
