### ISSUE TITLE
支持修改房间的 expect members

### ISSUE THREAD

**Issue by ylgrgyq** [leancloud/Play-SDK-JS#206]
来自这里：
https://github.com/leancloud/leangame/issues/176

wiki： https://github.com/leancloud/leangame/wiki/game-server-%E5%8D%8F%E8%AE%AE:-room-%E7%9B%B8%E5%85%B3#room-%E7%B3%BB%E7%BB%9F%E5%B1%9E%E6%80%A7%E4%BF%AE%E6%94%B9

废弃之前设置 open 和 visible 的方式，改用新的方式并支持修改 expect members，稍后支持修改 max members。

@onerain88

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/215
