### ISSUE TITLE
支持设置 maxMembers

### ISSUE THREAD

**Issue by ylgrgyq** [leancloud/Play-SDK-JS#207]
wiki: 
https://github.com/leancloud/leangame/wiki/game-server-%E5%8D%8F%E8%AE%AE:-room-%E7%9B%B8%E5%85%B3#%E8%AE%BE%E7%BD%AE-room-%E6%9C%80%E5%A4%A7%E6%88%90%E5%91%98%E6%95%B0

issue: https://github.com/leancloud/leangame/issues/511

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/215
