### ISSUE TITLE
增加接口：创建房间时指定 Multiplayer Server 中的某一个 plugin

### ISSUE THREAD

**Issue by nicecui** [leancloud/Play-SDK-JS#216]
示例：
```js
const options = {
  plugin : "nameOfSomePlugin"
};
client.createRoom({ roomOptions:options });
```

附：服务端的 Plugin  实现：https://github.com/leancloud/leangame/wiki/%E5%AE%9E%E7%8E%B0-Multiplayer-Server-Plugin#%E5%AE%9E%E7%8E%B0-pluginfactory-%E6%9D%A5%E5%88%9B%E5%BB%BA-multiplayer-server-plugin

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/releases/tag/v0.18.0-beta.4
