### ISSUE TITLE
random add/match 增加对 expectMembers 的支持

### ISSUE THREAD

**Issue by liuchong** [leancloud/Play-SDK-JS#220]
现在random add/match 的时候已支持 expectMembers 参数，请参考文档

[随机加入 room](https://github.com/leancloud/leangame/wiki/lobby-%E5%8D%8F%E8%AE%AE/b545e1a0acd54373985f06e5155b9622c7b4d6a2#%E9%9A%8F%E6%9C%BA%E5%8A%A0%E5%85%A5-room)
[随机匹配 room 但不加入](https://github.com/leancloud/leangame/wiki/lobby-%E5%8D%8F%E8%AE%AE/b545e1a0acd54373985f06e5155b9622c7b4d6a2#%E9%9A%8F%E6%9C%BA%E5%8C%B9%E9%85%8D-room-%E4%BD%86%E4%B8%8D%E5%8A%A0%E5%85%A5)

更多信息请参考 https://github.com/leancloud/leangame/issues/532

**Comment by onerain88** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/223
