### ISSUE TITLE
ReferenceError: proto is not defined

### ISSUE THREAD

**Issue by quanNullable** [leancloud/Play-SDK-JS#236]
微信小程序在require play-weapp.js后报
ReferenceError: proto is not defined
    at play-weapp.js:10146
    at createCommonjsModule (play-weapp.js:14)
    at play-weapp.js:10112
    at play-weapp.js:2
    at play-weapp.js:5
请问是什么原因？

**Comment by onerain88** [comment]
请问是使用游戏引擎导出的「微信小游戏」还是「微信小程序」项目？

**Comment by quanNullable** [comment]
> 请问是使用游戏引擎导出的「微信小游戏」还是「微信小程序」项目？

新建的微信小程序，然后下载的最新版play-weapp.js

**Comment by onerain88** [comment]
我试了一下，是 google-protobuf 生成代码不符合微信小程序的规范，所以需要魔改一下生成代码。
我重新打包了一份 play-weapp.js，在小程序下测试没有如上的报错了，请下载试试。
[play-weapp.zip](https://github.com/leancloud/Play-SDK-JS/files/3938969/play-weapp.zip)

**Comment by quanNullable** [comment]
非常感谢，我试了下，不报错了，并且可以成功初始化

**Comment by onerain88** [comment]
非常感谢反馈，下个版本我们会修复这个问题
