### ISSUE TITLE
cocos creator 引入TS声明不能使用  (play.d.ts)  

### ISSUE THREAD

**Issue by Excalibur0w0** [leancloud/Play-SDK-JS#47]
-- 看了下d.ts 有个RoomOptions，这个是自行配置吗？
import RoomOptions from './src/RoomOptions';

另外，直接引入报错信息是
![image](https://user-images.githubusercontent.com/22142290/43111744-1e8232b6-8f25-11e8-900f-1b400405e147.png)

**Comment by onerain88** [comment]
为了适应 JS 的习惯，已经将 RoomOptions 类型去掉了，请重新下载 sdk
https://github.com/leancloud/Play-SDK-JS/releases

2018-07-24 9:39 GMT+08:00 Excalibur0w0 <notifications@github.com>:

**Comment by Excalibur0w0** [comment]
@onerain88  请问是TS声明还没有更新吗？

**Comment by onerain88** [comment]
我刚刚更新了一下 TS 接口 v0.9.1 
https://github.com/leancloud/Play-SDK-JS/releases
抱歉 TS 版本我们还没有经过太多测试，建议使用 JS 接口。
稍后我们会完善 TS

**Comment by Excalibur0w0** [comment]
@onerain88  好的，感谢！
