### ISSUE TITLE
引入 play.js 后 cocos creator 构建出错

### ISSUE THREAD

**Issue by Excalibur0w0** [leancloud/Play-SDK-JS#49]
引入play.js 预览游戏正常，进行构建发布

![image](https://user-images.githubusercontent.com/22142290/43117196-26259508-8f3e-11e8-9610-3ca8534b684c.png)

报 debug 模块未找到的错误
![image](https://user-images.githubusercontent.com/22142290/43117087-94ca49d2-8f3d-11e8-85c7-065ea03ce269.png)

注释掉play.js中所有的debug引用
构建成功， 但是用微信开发者工具 打开 小游戏后报错
![image](https://user-images.githubusercontent.com/22142290/43117582-256af692-8f40-11e8-8b53-57afb2800ed0.png)

**Comment by Excalibur0w0** [comment]
补充，pc 的h5构建此时不报错

**Comment by onerain88** [comment]
非常感谢你的测试，是由于 debug 库导入方式不对，现已修正，请重新下载 v0.9.2
https://github.com/leancloud/Play-SDK-JS/releases

**Comment by Excalibur0w0** [comment]
@onerain88 
1、目前支持**微信小游戏**开发吗？
      我使用_cocos creator_ 构建成微信小游戏 会报 charAt undefined 的错误
      直接原生 **微信小游戏** 引入也会报这个错误
2、小程序能使用这个SDK吗？
      我试图在 **微信小程序** 里导入 这个sdk 会报adapter 不是 function的错误

**Comment by onerain88** [comment]
使用 v0.10.0 版本构建微信小游戏是没有报错的
请问你是什么环境？

**Comment by Excalibur0w0** [comment]
@onerain88 
我更新了play.js 到 0.10.0
此时使用 require 引入
![image](https://user-images.githubusercontent.com/22142290/43142150-4b2b2b46-8f8a-11e8-9097-29c38913a009.png)

似乎无法找到 play.js的模块
我稍后试试其它的
