### ISSUE TITLE
在cocos creator v1.9中 引入sdk v0.9.2 以及之后的版本cocos控制台报错

### ISSUE THREAD

**Issue by Excalibur0w0** [leancloud/Play-SDK-JS#60]
通过 require形式引入
```
//  helloworld.js
const play = require('../play-v0.10.0')
const play2 = require('../play-v0.9.2')
const play3 = require('../play-v0.9.1')
const play4 = require('../play-v0.9.0')
const play5 = require('../play-v0.8.0')

cc.Class({
    extends: cc.Component,

    properties: {
        
    },

    onLoad: function () {
        
    },

    update: function (dt) {

    },
});

```
这是存放的文件目录
![list](https://user-images.githubusercontent.com/22142290/43143529-81c7d4da-8f8d-11e8-84b1-3e0b0986902a.png)

这是报错信息
![image](https://user-images.githubusercontent.com/22142290/43143592-9dc31a64-8f8d-11e8-973d-7cfee3ce3f03.png)

非期望的行为
引入play.js v0.9.2 以及之后的版本  cocos控制台报错 找不到模块

期望：
能找到并正确读取到play对象

**Comment by onerain88** [comment]
请 clone 一份 Demo 工程，我这边构建是没有问题的。
[快速入门](https://github.com/leancloud/Play-Quick-Start-JS)

**Comment by Excalibur0w0** [comment]
@onerain88 您好， 我clone了一份Demo， 
在构建成微信小游戏的时候报这个错误
![image](https://user-images.githubusercontent.com/22142290/43175181-715ddb9a-8ff0-11e8-9742-2b207c648e73.png)

**Comment by Excalibur0w0** [comment]
构建是没有问题的，用微信开发者工具打开， 控制台会报错。

**Comment by Excalibur0w0** [comment]
您的微信开发者工具 报错吗？

**Comment by onerain88** [comment]
稍等，我看一下

**Comment by onerain88** [comment]
我们复现了你说的小程序运行的问题，现在发布了 v0.10.1 修复了这个问题。
[v0.10.1](https://github.com/leancloud/Play-SDK-JS/releases)
目前已测试通过的平台：Mac，Web，iOS，微信小游戏。
再次感谢你的测试！
