### ISSUE TITLE
SDK 支持选择支持微信的节点

### ISSUE THREAD

**Issue by ylgrgyq** [leancloud/Play-SDK-JS#94]
详细写在这里：https://github.com/leancloud/leangame/issues/305

**Comment by leeyeh** [comment]
这其实是 SDK 内部的逻辑，如果我们有能力判断出来最好不要增加一个用户需要关心的参数。参考：

https://github.com/leancloud/js-realtime-sdk/blob/master/src/realtime.js#L318

**Comment by onerain88** [comment]
这样判断挺好，我改一下

**Comment by leeyeh** [comment]
https://github.com/leancloud/Play-SDK-JS/pull/98
https://github.com/leancloud/Play-SDK-JS/pull/99
